let Ussf={
  student:{
    bob:{
      name:"bob",
      img:"link",
      gender:0,//0 is male, 1 is female, 2 is other
      race:"black",
      annualIncome:80000,
      gpa:3.7,
      age:18,
      hasLegacy:true,
      isFirstGeneration:false,
      requiresFinancialAid:false,
      isAthlete:true,
      preferredMajor:"computer science",
      extracurriculars:["tuba","volunteers for Habitat for Humanity","scoops ice cream at Baskin Robbins"],
      essay:"The quick brown fox jumps over the lazy dog",
      isEarlyDecision:true
    },
    jane:{
      name:"jane",
      img:"link",
      gender:1,
      race:"caucasian",
      annualIncome:70000,
      gpa:3.6,
      age:18,
      hasLegacy:false,
      isFirstGeneration:true,
      requiresFinancialAid:true,
      isAthlete:true,
      preferredMajor:"political science",
      extracurriculars:["cheer","volunteers for local soup kitchen","tutors kids in algebra and history"],
      essay:"Belle Delphine did 9/11",
      isEarlyDecision:true
    }
  },
  college:{
    Princeton:{
      schoolWealth:0,
      schoolDiversity:0,
      schoolSports:0,
      schoolGPA:0,
      schoolLegacy:0,
      requiredSchoolLegacy:60,
      requiredSchoolWealth:80,
      requiredSchoolDiversity:20,
      requiredSchoolSports:70,
      requiredSchoolGPA:80,
      students:[],
      numOfStudents:0
    },
    // CHANGE ALL GPA QUOTAS TO 0 to 4.0 scale
    Harvard:{
      schoolWealth:0,
      schoolDiversity:0,
      schoolSports:0,
      schoolGPA:0,
      schoolLegacy:0,
      requiredSchoolLegacy:60,
      requiredSchoolWealth:80,
      requiredSchoolDiversity:20,
      requiredSchoolSports:60,
      requiredSchoolGPA:80,
      students:[],
      numOfStudents:0
    },
    Yale:{
      schoolWealth:0,
      schoolDiversity:0,
      schoolSports:0,
      schoolGPA:0,
      schoolLegacy:0,
      requiredSchoolLegacy:25,
      requiredSchoolWealth:75,
      requiredSchoolDiversity:30,
      requiredSchoolSports:65,
      requiredSchoolGPA:90,
      students:[],
      numOfStudents:0
    },
    Stanford:{
      schoolWealth:0,
      schoolDiversity:0,
      schoolSports:0,
      schoolGPA:0,
      schoolLegacy:0,
      requiredSchoolLegacy:15,
      requiredSchoolWealth:70,
      requiredSchoolDiversity:20,
      requiredSchoolSports:80,
      requiredSchoolGPA:89,
      students:[],
      numOfStudents:0
    },
    Mit:{
      schoolWealth:0,
      schoolDiversity:0,
      schoolSports:0,
      schoolGPA:0,
      schoolLegacy:0,
      requiredSchoolLegacy:5,
      requiredSchoolWealth:70,
      requiredSchoolDiversity:35,
      requiredSchoolSports:40,
      requiredSchoolGPA:92,
      students:[],
      numOfStudents:0
    },
    UChicago:{
      schoolWealth:0,
      schoolDiversity:0,
      schoolSports:0,
      schoolGPA:0,
      schoolLegacy:0,
      requiredSchoolLegacy:12,
      requiredSchoolWealth:60,
      requiredSchoolDiversity:5,
      requiredSchoolSports:40,
      requiredSchoolGPA:75,
      students:[],
      numOfStudents:0
    },
    CalTech:{
      schoolWealth:0,
      schoolDiversity:0,
      schoolSports:0,
      schoolGPA:0,
      schoolLegacy:0,
      requiredSchoolLegacy:15,
      requiredSchoolWealth:50,
      requiredSchoolDiversity:30,
      requiredSchoolSports:10,
      requiredSchoolGPA:88,
      students:[],
      numOfStudents:0
    },
    Georgetown:{
      schoolWealth:0,
      schoolDiversity:0,
      schoolSports:0,
      schoolGPA:0,
      schoolLegacy:0,
      requiredSchoolLegacy:35,
      requiredSchoolWealth:45,
      requiredSchoolDiversity:15,
      requiredSchoolSports:10,
      requiredSchoolGPA:65,
      students:[],
      numOfStudents:0
    },
    UPenn:{
      schoolWealth:0,
      schoolDiversity:0,
      schoolSports:0,
      schoolGPA:0,
      schoolLegacy:0,
      requiredSchoolLegacy:15,
      requiredSchoolWealth:40,
      requiredSchoolDiversity:30,
      requiredSchoolSports:30,
      requiredSchoolGPA:70,
      students:[],
      numOfStudents:0
    },
    Northwestern:{
      schoolWealth:0,
      schoolDiversity:0,
      schoolSports:0,
      schoolGPA:0,
      schoolLegacy:0,
      requiredSchoolLegacy:15,
      requiredSchoolWealth:30,
      requiredSchoolDiversity:40,
      requiredSchoolSports:15,
      requiredSchoolGPA:65,
      students:[],
      numOfStudents:0
    },
    Berkeley:{
      schoolWealth:0,
      schoolDiversity:0,
      schoolSports:0,
      schoolGPA:0,
      schoolLegacy:0,
      requiredSchoolLegacy:10,
      requiredSchoolWealth:30,
      requiredSchoolDiversity:35,
      requiredSchoolSports:30,
      requiredSchoolGPA:65,
      students:[],
      numOfStudents:0
    },
    CarnegieMellon:{
      schoolWealth:0,
      schoolDiversity:0,
      schoolSports:0,
      schoolGPA:0,
      schoolLegacy:0,
      requiredSchoolLegacy:20,
      requiredSchoolWealth:35,
      requiredSchoolDiversity:40,
      requiredSchoolSports:30,
      requiredSchoolGPA:50,
      students:[],
      numOfStudents:0
    },
    Cornell:{
      schoolWealth:0,
      schoolDiversity:0,
      schoolSports:0,
      schoolGPA:0,
      schoolLegacy:0,
      requiredSchoolLegacy:30,
      requiredSchoolWealth:70,
      requiredSchoolDiversity:25,
      requiredSchoolSports:35,
      requiredSchoolGPA:75,
      students:[],
      numOfStudents:0
    },
    Ucla:{
      schoolWealth:0,
      schoolDiversity:0,
      schoolSports:0,
      schoolGPA:0,
      schoolLegacy:0,
      requiredSchoolLegacy:15,
      requiredSchoolWealth:60,
      requiredSchoolDiversity:40,
      requiredSchoolSports:45,
      requiredSchoolGPA:65,
      students:[],
      numOfStudents:0
    },
    Duke:{
      schoolWealth:0,
      schoolDiversity:0,
      schoolSports:0,
      schoolGPA:0,
      schoolLegacy:0,
      requiredSchoolLegacy:35,
      requiredSchoolWealth:60,
      requiredSchoolDiversity:20,
      requiredSchoolSports:30,
      requiredSchoolGPA:80,
      students:[],
      numOfStudents:0
    },
    WilliamsCollege:{
      schoolWealth:0,
      schoolDiversity:0,
      schoolSports:0,
      schoolGPA:0,
      schoolLegacy:0,
      requiredSchoolLegacy:10,
      requiredSchoolWealth:40,
      requiredSchoolDiversity:30,
      requiredSchoolSports:10,
      requiredSchoolGPA:35,
      students:[],
      numOfStudents:0
    },
    Amherst:{
      schoolWealth:0,
      schoolDiversity:0,
      schoolSports:0,
      schoolGPA:0,
      schoolLegacy:0,
      requiredSchoolLegacy:20,
      requiredSchoolWealth:50,
      requiredSchoolDiversity:55,
      requiredSchoolSports:15,
      requiredSchoolGPA:60,
      students:[],
      numOfStudents:0
    },
    Swarthmore:{
      schoolWealth:0,
      schoolDiversity:0,
      schoolSports:0,
      schoolGPA:0,
      schoolLegacy:0,
      requiredSchoolLegacy:10,
      requiredSchoolWealth:20,
      requiredSchoolDiversity:35,
      requiredSchoolSports:30,
      requiredSchoolGPA:40,
      students:[],
      numOfStudents:0
    },
    accept:function(stud,coll){
      if(!coll.students.includes(stud)){
        coll.students.push(stud);
        coll.numOfStudents++;
        if(stud.hasLegacy){
          coll.schoolLegacy++;
        }
        if(stud.isAthlete){
          coll.schoolSports++;
        }
        if(stud.requiresFinancialAid){
          coll.schoolWealth++;
        }
        coll.schoolDiversity+=Ussf.college.computeDiversity(stud);
        coll.schoolGPA+=stud.gpa;
      } else{
        console.log("Student is already enrolled.");
        alert("Student is already enrolled.");
      }
    },
    computeDiversity:function(stud){
      let total=0;
      total+=stud.gender;
      if(stud.race=="caucasian"){
        total+=1;
      } else if(stud.race!="asian"){
        total+=2;
      }
      return(total);
    },
    calculateGPA:function(coll){
      return(coll.schoolGPA/coll.numOfStudents);
    },
    calculateLegacy:function(coll){
      return(coll.schoolLegacy/coll.numOfStudents*100);
    },
    calculateSports:function(coll){
      return(coll.schoolSports/coll.numOfStudents*100);
    },
    calculateDiversity:function(coll){
      return(coll.schoolDiversity/coll.numOfStudents*100);
    },
    calculateWealth:function(coll){
      return(coll.schoolWealth/coll.numOfStudents*100);
    }
  }
}
Ussf.college.accept(Ussf.student.bob,Ussf.college.Princeton);
console.log(Ussf.college.calculateGPA(Ussf.college.Princeton));
console.log(Ussf.college.calculateLegacy(Ussf.college.Princeton));
console.log(Ussf.college.calculateSports(Ussf.college.Princeton));
console.log(Ussf.college.calculateDiversity(Ussf.college.Princeton));
Ussf.college.accept(Ussf.student.jane,Ussf.college.Princeton);
console.log(Ussf.college.calculateGPA(Ussf.college.Princeton));
console.log(Ussf.college.calculateLegacy(Ussf.college.Princeton));
console.log(Ussf.college.calculateSports(Ussf.college.Princeton));
console.log(Ussf.college.Princeton.numOfStudents);
console.log(Ussf.college.calculateDiversity(Ussf.college.Princeton));
console.log(Ussf.college.calculateWealth(Ussf.college.Princeton));
console.log(Ussf.college.Princeton.students);
